### PR TITLE
fix docker and updated to latest version of ubuntu

### PR DESCRIPTION
**Pull request by anakwaboe4**
hey,

if fixed it so it works with fishtest of today and uses the ubuntu 22.04.

I also made my own docker if you would never merge it.

greeting anakwaboe4

### CODE REVIEW

**Comment by marcelorodrigo** [comment]
Thanks @anakwaboe4 for your contribution.
I've tried to run your changes, but with the Ubuntu 22.04 I got exceptions running games, such as:

```
Step 1/4. Building instrumented executable ...
make ARCH=x86-64 COMP=gcc gcc-profile-make
make[1]: Entering directory '/fishtest/worker/tmplwknlocp/dubslow-Stockfish-64bcba0/src'
make ARCH=x86-64 COMP=gcc \
EXTRACXXFLAGS='-fprofile-generate=profdir' \
EXTRACXXFLAGS+= \
EXTRALDFLAGS='-lgcov' \
all
make[2]: Entering directory '/fishtest/worker/tmplwknlocp/dubslow-Stockfish-64bcba0/src'
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2 -flto   -c -o benchmark.o benchmark.cpp
make[2]: Leaving directory '/fishtest/worker/tmplwknlocp/dubslow-Stockfish-64bcba0/src'
make[1]: Leaving directory '/fishtest/worker/tmplwknlocp/dubslow-Stockfish-64bcba0/src'

Exception running games:
Executing make -j 1 profile-build ARCH=x86-64 COMP=gcc failed. Error: ['g++: error: unrecognized command-line option ‘-m64’\n', 'g++: error: unrecognized command-line option ‘-msse’\n', 'g++: error: unrecognized command-line option ‘-msse2’\n', 'make[2]: *** [<builtin>: benchmark.o] Error 1\n', 'make[1]: *** [Makefile:955: gcc-profile-make] Error 2\n', 'make: *** [Makefile:800: profile-build] Error 2\n']
```

Did you had similar issues?

**Comment by anakwaboe4** [comment]
i do not have those issue, i will need to look into them. 
i'll ask on the stockfish discord and see if they know.

**Comment by anakwaboe4** [comment]
J. VandeVondele (current maintainer of stockfish) wrote:
not so clear, gcc seems not to recognize standard compiler options. I'm wondering if there is something wrong with line termination (\n appears in this error message).

still for me it build successfully.
try https://hub.docker.com/r/laurentaerens/fishtest (I've pushed them to my own docker hub because i wasn't sure they would ever get merged)

**Comment by marcelorodrigo** [comment]
It could be something related to arm64? I'm testing on Apple M1.
Let me find a x64 machine to test it and then we can move further.

**Comment by anakwaboe4** [comment]
yeah it is, while arm64 is supported i think this docker might struggle with that.
I will look into making it both arm64 and x86-64 compatible in the future.

**Comment by anakwaboe4** [comment]
yeah i need to change the base Ubuntu image. Will create a arm64 docker tonight.

**Comment by marcelorodrigo** [comment]
Definitely. Let's merge this one to not make it waiting longer.
By the way, I have also another idea that could be really nice: create the base image, but update the fishtest code repo on the fly as the image runs.

This means every time you spin up a container, try to update the code on the volume with a git pull and get the fresh code always: meaning we can always run the latest version from master. Let's think about it and see if it's a good idea.

Thanks @anakwaboe4 for your PR, good job :-)

**Pull request merged**
